FROM base-swift-ubuntu:latest

# this is temporary. upstream playbooks should be adjusted to match
ADD tmp_playbooks/ /tmp_playbooks

RUN ansible-playbook -i "localhost," -c local /tmp_playbooks/setup_proxy.yaml

ENTRYPOINT ["swift-proxy-server", "/etc/swift/proxy-server.conf"]
