#!/bin/bash

# This script is included to set up one-replica rings. The "ip" used is
# the hostname as defined in the docker-compose file.

set -e

cd /etc/swift

rm -f *.builder *.ring.gz backups/*.builder backups/*.ring.gz

swift-ring-builder object.builder create 10 1 1
swift-ring-builder object.builder add \
    --region 1 \
    --zone 1 \
    --ip object \
    --port 6200 \
    --device d1 \
    --weight 1
swift-ring-builder object.builder rebalance
swift-ring-builder container.builder create 10 1 1
swift-ring-builder container.builder add \
    --region 1 \
    --zone 1 \
    --ip container \
    --port 6201 \
    --device d1 \
    --weight 1
swift-ring-builder container.builder rebalance
swift-ring-builder account.builder create 10 1 1
swift-ring-builder account.builder add \
    --region 1 \
    --zone 1 \
    --ip account \
    --port 6202 \
    --device d1 \
    --weight 1
swift-ring-builder account.builder rebalance
