- name: update pip
  pip:
    name: pip
    state: latest

- name: install libec build tools
  apk: name={{item}} state=installed
  with_items:
    - gcc
    - musl-dev
    - autoconf
    - automake
    - make
    - libtool
    - zlib-dev

- name: download libec code
  git:
    repo: https://github.com/openstack/liberasurecode.git
    dest: /usr/local/src/liberasurecode

- name: install libec from source
  shell: ./autogen.sh && ./configure && make && sudo make install && ldconfig
  args:
    chdir: /usr/local/src/liberasurecode

- name: install bindep
  pip:
    # specify github url until https://review.openstack.org/#/c/564650/ is available on pypi
    name: git+https://github.com/openstack-infra/bindep.git#egg=bindep
    state: latest

- name: run bindep
  command: bindep platform:apk -b
  args:
    chdir: /usr/local/src/swift
  register: bindep_output_alpine
  failed_when: ( bindep_output_alpine.rc not in [ 0, 1 ] )

- name: install requirements from bindep
  apk:
    name: "{{ bindep_output_alpine.stdout_lines }}"
  when:
    - bindep_output_alpine.rc == 1

